"""add ai_queries table

Revision ID: 85f16be68bdd
Revises: f2ee9bfbe6f5
Create Date: 2025-08-31 15:00:33.353329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85f16be68bdd'
down_revision = 'f2ee9bfbe6f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query_text', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('response_text', sa.Text(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('response_json')
        batch_op.drop_column('ingredients_text')
        batch_op.drop_column('model')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('ingredients_text', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('response_json', mysql.TEXT(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('response_text')
        batch_op.drop_column('query_text')

    # ### end Alembic commands ###
